export { default as PHome } from './PHome'
export { default as PGame } from './PGame'
export { default as PGameChronology } from './PGameChronology'
export { default as PLibrary } from './PLibrary'
export { default as PTemplate } from './PTemplate'
export { default as PPastGames } from './PPastGames'
